# Recommendation System Notebook
- User based recommendation
- User based prediction & evaluation
- Item based recommendation
- Item based prediction & evaluation
- Final Item-based recommendation system

In [1]:
# import libraties
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df  = pd.read_csv('Dataset/sample30.csv')
df.head()

id            brand  \
0  AV13O1A8GV-KLJ3akUyj  Universal Music   
1  AV14LG0R-jtxr-f38QfS         Lundberg   
2  AV14LG0R-jtxr-f38QfS         Lundberg   
3  AV16khLE-jtxr-f38VFn              K-Y   
4  AV16khLE-jtxr-f38VFn              K-Y   

                                          categories  \
0  Movies, Music & Books,Music,R&b,Movies & TV,Mo...   
1  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
2  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
3  Personal Care,Medicine Cabinet,Lubricant/Sperm...   
4  Personal Care,Medicine Cabinet,Lubricant/Sperm...   

                         manufacturer  \
0  Universal Music Group / Cash Money   
1                            Lundberg   
2                            Lundberg   
3                                 K-Y   
4                                 K-Y   

                                         name              reviews_date  \
0   Pink Friday: Roman Reloaded Re-Up (w/dvd)  2012-11-30T06:21:45.000Z   
1  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
2  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
3            K-Y Love Sensuality Pleasure Gel  2016-01-06T00:00:00.000Z   
4            K-Y Love Sensuality Pleasure Gel  2016-12-21T00:00:00.000Z   

  reviews_didPurchase reviews_doRecommend  reviews_rating  \
0                 NaN                 NaN               5   
1                True                 NaN               5   
2                True                 NaN               5   
3               False               False               1   
4               False               False               1   

                                        reviews_text reviews_title  \
0  i love this album. it's very good. more to the...  Just Awesome   
1  Good flavor. This review was collected as part...          Good   
2                                       Good flavor.          Good   
3  I read through the reviews on here before look...  Disappointed   
4  My husband bought this gel for us. The gel cau...    Irritation   

  reviews_userCity reviews_userProvince reviews_username user_sentiment  
0      Los Angeles                  NaN           joshua       Positive  
1              NaN                  NaN        dorothy w       Positive  
2              NaN                  NaN        dorothy w       Positive  
3              NaN                  NaN          rebecca       Negative  
4              NaN                  NaN        walker557       Negative

In [3]:
df.nunique()

id                        271
brand                     214
categories                270
manufacturer              227
name                      271
reviews_date             6857
reviews_didPurchase         2
reviews_doRecommend         2
reviews_rating              5
reviews_text            27282
reviews_title           18535
reviews_userCity          977
reviews_userProvince       42
reviews_username        24914
user_sentiment              2
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   id                    30000 non-null  object
 1   brand                 30000 non-null  object
 2   categories            30000 non-null  object
 3   manufacturer          29859 non-null  object
 4   name                  30000 non-null  object
 5   reviews_date          29954 non-null  object
 6   reviews_didPurchase   15932 non-null  object
 7   reviews_doRecommend   27430 non-null  object
 8   reviews_rating        30000 non-null  int64 
 9   reviews_text          30000 non-null  object
 10  reviews_title         29810 non-null  object
 11  reviews_userCity      1929 non-null   object
 12  reviews_userProvince  170 non-null    object
 13  reviews_username      29937 non-null  object
 14  user_sentiment        29999 non-null  object
dtypes: int64(1), object(14)
memory usage

So there are 271 unique products with id and name having unique value. So we will keep only id for our calculation.

There is column rating which is also a required column for prediction.

There are also 24914 unique usernames which is to be taken.

In [5]:
ratings= df[['id','reviews_rating','reviews_username']]
ratings.head()

id  reviews_rating reviews_username
0  AV13O1A8GV-KLJ3akUyj               5           joshua
1  AV14LG0R-jtxr-f38QfS               5        dorothy w
2  AV14LG0R-jtxr-f38QfS               5        dorothy w
3  AV16khLE-jtxr-f38VFn               1          rebecca
4  AV16khLE-jtxr-f38VFn               1        walker557

In [6]:
ratings['id'].nunique()

271

In [7]:
ratings['reviews_username'].nunique()

24914

In [8]:
ratings.shape

(30000, 3)

Let's check for duplicate rows.

In [9]:
ratings[ratings.duplicated()]

id  reviews_rating reviews_username
2      AV14LG0R-jtxr-f38QfS               5        dorothy w
12     AV16khLE-jtxr-f38VFn               1          jds1992
44     AV1h6Gu0glJLPUi8IjA_               4             solo
79     AV1l8zRZvKc47QAVhnAv               3    mylifeinheels
90     AV1l8zRZvKc47QAVhnAv               3    mylifeinheels
...                     ...             ...              ...
29807  AVpfW8y_LJeJML437ySW               5         joycakes
29827  AVpfW8y_LJeJML437ySW               5          emily95
29841  AVpfW8y_LJeJML437ySW               5   brookieboo1994
29921  AVpfW8y_LJeJML437ySW               5     talmariejohn
29944  AVpfW8y_LJeJML437ySW               5          filo123

[2237 rows x 3 columns]

This might be possible as the user have bought the same product multiple times and reviewed it afterwards. Let's check for some more arbitarory users

In [10]:
df.loc[(df['id']=='AV1YGDqsGV-KLJ3adc-O') & (df['reviews_username']== 'laura'),:]

id   brand  \
695  AV1YGDqsGV-KLJ3adc-O  Windex   
746  AV1YGDqsGV-KLJ3adc-O  Windex   

                                            categories manufacturer  \
695  Household Essentials,Cleaning Supplies,Glass C...       Windex   
746  Household Essentials,Cleaning Supplies,Glass C...       Windex   

                                                  name  \
695  Windex Original Glass Cleaner Refill 67.6oz (2...   
746  Windex Original Glass Cleaner Refill 67.6oz (2...   

                 reviews_date reviews_didPurchase reviews_doRecommend  \
695  2014-10-16T00:00:00.000Z               False               False   
746  2015-05-25T00:00:00.000Z               False               False   

     reviews_rating                                       reviews_text  \
695               1  Why did they change the formula it's awful . I...   
746               2  Windex doesn't clean mirrors, glass like it us...   

                  reviews_title reviews_userCity reviews_userProvince  \
695           BAD very very BAD              NaN                  NaN   
746  Did You Change Ingredients              NaN                  NaN   

    reviews_username user_sentiment  
695            laura       Negative  
746            laura       Positive

In [11]:
df.loc[(df['id']=='AVpfRTh1ilAPnD_xYic2') & (df['reviews_username']== 'dusty'),:]

id   brand  \
27321  AVpfRTh1ilAPnD_xYic2  Disney   
27375  AVpfRTh1ilAPnD_xYic2  Disney   
27442  AVpfRTh1ilAPnD_xYic2  Disney   
27454  AVpfRTh1ilAPnD_xYic2  Disney   
28150  AVpfRTh1ilAPnD_xYic2  Disney   

                                              categories manufacturer  \
27321  Movies, Music & Books,Movies,Kids' & Family,Wa...  Walt Disney   
27375  Movies, Music & Books,Movies,Kids' & Family,Wa...  Walt Disney   
27442  Movies, Music & Books,Movies,Kids' & Family,Wa...  Walt Disney   
27454  Movies, Music & Books,Movies,Kids' & Family,Wa...  Walt Disney   
28150  Movies, Music & Books,Movies,Kids' & Family,Wa...  Walt Disney   

                                                    name  \
27321  Planes: Fire Rescue (2 Discs) (includes Digita...   
27375  Planes: Fire Rescue (2 Discs) (includes Digita...   
27442  Planes: Fire Rescue (2 Discs) (includes Digita...   
27454  Planes: Fire Rescue (2 Discs) (includes Digita...   
28150  Planes: Fire Rescue (2 Discs) (includes Digita...   

                   reviews_date reviews_didPurchase reviews_doRecommend  \
27321  2014-12-05T00:00:00.000Z                 NaN                True   
27375  2014-12-24T00:00:00.000Z                 NaN                True   
27442  2015-08-05T00:00:00.000Z                 NaN                True   
27454  2016-02-01T00:00:00.000Z                 NaN                True   
28150  2014-11-07T00:00:00.000Z                 NaN                True   

       reviews_rating                                       reviews_text  \
27321               4  I enjoyed the graphics and the moral of the st...   
27375               4  Great follow up to the first Planes movie, thi...   
27442               4  good flick my kids enjoyed this movie and it i...   
27454               4  Great movie for my little ones. The extra feat...   
28150               5  Kids as well as adults will love this movie. I...   

                           reviews_title reviews_userCity  \
27321                 Good animated show              NaN   
27375                          great job              NaN   
27442                         good flick              NaN   
27454                Excellent condition              NaN   
28150  The best Disney/Pixar movie EVER!              NaN   

      reviews_userProvince reviews_username user_sentiment  
27321                  NaN            dusty       Positive  
27375                  NaN            dusty       Positive  
27442                  NaN            dusty       Positive  
27454                  NaN            dusty       Positive  
28150                  NaN            dusty       Positive

In [12]:
df.loc[df['id']== 'AV14LG0R-jtxr-f38QfS',:]

id     brand  \
1  AV14LG0R-jtxr-f38QfS  Lundberg   
2  AV14LG0R-jtxr-f38QfS  Lundberg   

                                          categories manufacturer  \
1  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...     Lundberg   
2  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...     Lundberg   

                                         name              reviews_date  \
1  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
2  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   

  reviews_didPurchase reviews_doRecommend  reviews_rating  \
1                True                 NaN               5   
2                True                 NaN               5   

                                        reviews_text reviews_title  \
1  Good flavor. This review was collected as part...          Good   
2                                       Good flavor.          Good   

  reviews_userCity reviews_userProvince reviews_username user_sentiment  
1              NaN                  NaN        dorothy w       Positive  
2              NaN                  NaN        dorothy w       Positive

As we can see user have actually made the purchases multiple times and then reviewed he itmes multiple times. So while creating the pivot table later in this notebook we will take average rating.

In [13]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   id                30000 non-null  object
 1   reviews_rating    30000 non-null  int64 
 2   reviews_username  29937 non-null  object
dtypes: int64(1), object(2)
memory usage: 703.2+ KB


There are some ratings where user_name is missing which is very less in number. So it's better to drop those rows.

In [14]:
ratings= ratings.loc[~ratings['reviews_username'].isnull(),:]
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29937 entries, 0 to 29999
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   id                29937 non-null  object
 1   reviews_rating    29937 non-null  int64 
 2   reviews_username  29937 non-null  object
dtypes: int64(1), object(2)
memory usage: 935.5+ KB


In [15]:
ratings['reviews_rating'].value_counts()

5    20792
4     6010
1     1373
3     1344
2      418
Name: reviews_rating, dtype: int64

In [16]:
ratings.reset_index(inplace=True, drop=True)

In [17]:
ratings.head()

id  reviews_rating reviews_username
0  AV13O1A8GV-KLJ3akUyj               5           joshua
1  AV14LG0R-jtxr-f38QfS               5        dorothy w
2  AV14LG0R-jtxr-f38QfS               5        dorothy w
3  AV16khLE-jtxr-f38VFn               1          rebecca
4  AV16khLE-jtxr-f38VFn               1        walker557

## Dividing the dataset into train and test

In [18]:
# Test and Train split of the dataset.
from sklearn.model_selection import train_test_split
train, test = train_test_split(ratings, test_size=0.30, random_state=31)

In [19]:
print(train.shape)
print(test.shape)

(20955, 3)
(8982, 3)


In [20]:
# Pivot the train ratings' dataset into matrix format in which columns are ids and the rows are username.
df_pivot = pd.pivot_table(train, values='reviews_rating', index='reviews_username',
                          columns='id', aggfunc='mean')

In [21]:
df_pivot.head(5)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            NaN                   NaN  ...   
01impala                           NaN                   NaN  ...   
02dakota                           NaN                   NaN  ...   
02deuce                            NaN                   NaN  ...   
06stidriver                        NaN                   NaN  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfrgjFLJeJML43BvCc  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN               

In [22]:
df_pivot.shape

(18212, 255)

### Creating dummy train & dummy test dataset
These dataset will be used for prediction 
- Dummy train will be used later for prediction of the pdts which has not been rated by the user. To ignore the pdts rated by the user, we will mark it as 0 during prediction. The pdts not rated by user is marked as 1 for prediction in dummy train dataset. 

- Dummy test will be used for evaluation. To evaluate, we will only make prediction on the pdts rated by the user. So, this is marked as 1. This is just opposite of dummy_train.

In [23]:
train.head()

id  reviews_rating reviews_username
5682   AVpf2tw1ilAPnD_xjflC               4             dwof
12507  AVpf3VOfilAPnD_xjpun               5         josie225
8504   AVpf3VOfilAPnD_xjpun               5          mellin1
5649   AVpf2tw1ilAPnD_xjflC               4        jerry64gd
21651  AVpfm8yiLJeJML43AYyu               1           augale

In [79]:
train['id'].nunique()

255

In [24]:
train['reviews_rating'].unique()

array([4, 5, 1, 3, 2], dtype=int64)

In [25]:
# Copy the train dataset into dummy_train
dummy_train = train.copy()

In [26]:
# The pdt not rated by user is marked as 1 for prediction. 
dummy_train['reviews_rating'] = 0

In [27]:
# Pivot the train ratings' dataset into matrix format in which columns are ids and the rows are username.
dummy_train = pd.pivot_table(dummy_train, values='reviews_rating', index='reviews_username',
                          columns='id', aggfunc='mean', fill_value=1)

In [28]:
dummy_train.head(10)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                              1                     1   
01impala                             1                     1   
02dakota                             1                     1   
02deuce                              1                     1   
06stidriver                          1                     1   
08dallas                             1                     1   
09mommy11                            1                     1   
1.11E+24                             1                     1   
1085                                 1                     1   
10ten                                1                     1   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                              1                     1   
01impala                             1                     1   
02dakota                             1                     1   
02deuce                              1                     1   
06stidriver                          1                     1   
08dallas                             1                     1   
09mommy11                            1                     1   
1.11E+24                             1                     1   
1085                                 1                     1   
10ten                                1                     1   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                              1                     1   
01impala                             1                     1   
02dakota                             1                     1   
02deuce                              1                     1   
06stidriver                          1                     1   
08dallas                             1                     1   
09mommy11                            1                     1   
1.11E+24                             1                     1   
1085                                 1                     1   
10ten                                1                     1   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                              1                     1   
01impala                             1                     1   
02dakota                             1                     1   
02deuce                              1                     1   
06stidriver                          1                     1   
08dallas                             1                     1   
09mommy11                            1                     1   
1.11E+24                             1                     1   
1085                                 1                     1   
10ten                                1                     0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                              1                     1  ...   
01impala                             1                     1  ...   
02dakota                             1                     1  ...   
02deuce                              1                     1  ...   
06stidriver                          1                     1  ...   
08dallas                             1                     1  ...   
09mommy11                            1                     1  ...   
1.11E+24                             1                     1  ...   
1085                                 1                     1  ...   
10ten                                1                     1  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username               

# User Similarity Matrix

## Using adjusted Cosine 

In [43]:
df_pivot.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            NaN                   NaN  ...   
01impala                           NaN                   NaN  ...   
02dakota                           NaN                   NaN  ...   
02deuce                            NaN                   NaN  ...   
06stidriver                        NaN                   NaN  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfrgjFLJeJML43BvCc  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN               

In [44]:
df_pivot.shape

(18212, 255)

In [48]:
df_pivot.loc['dwof','AVpf2tw1ilAPnD_xjflC']

4.0

### Normalising the rating of the movie for each user around 0 mean

In [49]:
mean = np.nanmean(df_pivot, axis=1)
mean.shape

(18212,)

In [32]:
df_subtracted= df_pivot.sub(mean, axis=0)

In [51]:
df_subtracted.sum(axis=1)

reviews_username
00sab00        0.0
01impala       0.0
02dakota       0.0
02deuce        0.0
06stidriver    0.0
              ... 
zuttle         0.0
zwithanx       0.0
zxcsdfd        0.0
zyiah4         0.0
zzz1127        0.0
Length: 18212, dtype: float64

In [52]:
df_subtracted.head(10)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   
08dallas                           NaN                   NaN   
09mommy11                          NaN                   NaN   
1.11E+24                           NaN                   NaN   
1085                               NaN                   NaN   
10ten                              NaN                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   
08dallas                           NaN                   NaN   
09mommy11                          NaN                   NaN   
1.11E+24                           NaN                   NaN   
1085                               NaN                   NaN   
10ten                              NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   
08dallas                           NaN                   NaN   
09mommy11                          NaN                   NaN   
1.11E+24                           NaN                   NaN   
1085                               NaN                   NaN   
10ten                              NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   
08dallas                           NaN                   NaN   
09mommy11                          NaN                   NaN   
1.11E+24                           NaN                   NaN   
1085                               NaN                   NaN   
10ten                              NaN                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            NaN                   NaN  ...   
01impala                           NaN                   NaN  ...   
02dakota                           NaN                   NaN  ...   
02deuce                            NaN                   NaN  ...   
06stidriver                        NaN                   NaN  ...   
08dallas                           NaN                   NaN  ...   
09mommy11                          NaN                   NaN  ...   
1.11E+24                           NaN                   NaN  ...   
1085                               NaN                   NaN  ...   
10ten                              NaN                   NaN  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username               

### Finding cosine similarity

In [85]:
from sklearn.metrics.pairwise import pairwise_distances

In [86]:
df_subtracted_array= df_subtracted.fillna(0).values

In [87]:
# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_subtracted_array, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [88]:
user_correlation.shape

(18212, 18212)

## Prediction - User User

Doing the prediction for the users which are positively related with other users, and not the users which are negatively related as we are interested in the users which are more similar to the current users. So, ignoring the correlation for values less than 0. 

In [60]:
user_correlation[user_correlation<0]=0
user_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [61]:
user_correlation.shape

(18212, 18212)

In [62]:
df_pivot.shape

(18212, 255)

In [64]:
df_pivot.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            NaN                   NaN  ...   
01impala                           NaN                   NaN  ...   
02dakota                           NaN                   NaN  ...   
02deuce                            NaN                   NaN  ...   
06stidriver                        NaN                   NaN  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfrgjFLJeJML43BvCc  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN               

Rating predicted by the user (for pdt rated as well as not rated) is the weighted sum of correlation with the pdt rating (as present in the rating dataset). 

In [66]:
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 1.55829543, 3.20256308,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [67]:
user_predicted_ratings.shape

(18212, 255)

Since we are interested only in the pdt not rated by the user, we will ignore the pdt rated by the user by making it zero. 

In [68]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
06stidriver                        0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            0.0              6.059436   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0.000000   
06stidriver                        0.0              0.000000   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
06stidriver                        0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            0.0              0.915079   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0.000000   
06stidriver                        0.0              0.000000   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            0.0                   0.0  ...   
01impala                           0.0                   0.0  ...   
02dakota                           0.0                   0.0  ...   
02deuce                            0.0                   0.0  ...   
06stidriver                        0.0                   0.0  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
00sab00                       0.545545                   0.0   
01impala                      0.000000                   0.0   
02dakota                      0.000000                   0.0   
02deuce                       0.000000                   0.0   
06stidriver                   0.000000                   0.0   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
06stidriver                        0.0                   0.0   

id                AVpfrgjFLJeJML43BvCc  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
06stidriver                        0.0                   0.0   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            0.0              1.558295   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0

### Finding the top 5 recommendation for the *user*

In [71]:
# Take the user ID as input.
user_input = (input("Enter your user name"))
print(user_input)

Enter your user name00sab00
00sab00


In [72]:
user_final_rating.head(2)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            0.0              6.059436   
01impala                           0.0              0.000000   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            0.0              0.915079   
01impala                           0.0              0.000000   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            0.0                   0.0  ...   
01impala                           0.0                   0.0  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
00sab00                       0.545545                   0.0   
01impala                      0.000000                   0.0   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   

id                AVpfrgjFLJeJML43BvCc  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            0.0              1.558295   
01impala                           0.0              0.000000   

id                AVpfv4TlilAPnD_xhjNS  AVpfvieo1cnluZ0-qdnu  
reviews_username                                              
00sab00                       3.202563                   0.0  
01impala                      0.000000                   0.0  

[2 rows x 255 columns]

In [73]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)[0:5]
d

id
AVpfPaoqLJeJML435Xk9    59.497748
AVpfRTh1ilAPnD_xYic2    35.729246
AVpf0eb2LJeJML43EVSt    30.742364
AVpf2tw1ilAPnD_xjflC    14.335169
AVpf3VOfilAPnD_xjpun    13.632461
Name: 00sab00, dtype: float64

# Evaluation - User User 

In [76]:
test.shape

(8982, 3)

In [77]:
# Find out the common users of test and train dataset.
common = test[test.reviews_username.isin(train.reviews_username)]
common.shape

(1976, 3)

In [89]:
common.head()

id  reviews_rating reviews_username
21122  AVpfm8yiLJeJML43AYyu               1             jjjj
8508   AVpf3VOfilAPnD_xjpun               5          jygibri
18688  AVpfJP1C1cnluZ0-e3Xy               4            jel08
22366  AVpfOmKwLJeJML435GM7               1          elena79
19250  AVpfJP1C1cnluZ0-e3Xy               5             angc

In [90]:
# convert into the user-movie matrix.
common_user_based_matrix = pd.pivot_table(common, values='reviews_rating', index='reviews_username',
                                          columns='id', aggfunc='mean')
common_user_based_matrix

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   
...                                ...                   ...   
zburt5                             NaN                   NaN   
zebras                             NaN                   NaN   
zippy                              NaN                   NaN   
zitro                              NaN                   NaN   
zxcsdfd                            NaN                   NaN   

id                AV1YlENIglJLPUi8IHsX  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   
...                                ...                   ...   
zburt5                             NaN                   NaN   
zebras                             NaN                   NaN   
zippy                              NaN                   NaN   
zitro                              NaN                   NaN   
zxcsdfd                            NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   
...                                ...                   ...   
zburt5                             NaN                   NaN   
zebras                             NaN                   NaN   
zippy                              NaN                   NaN   
zitro                              NaN                   NaN   
zxcsdfd                            NaN                   NaN   

id                AV1YneDPglJLPUi8IJyQ  AV1YqAaMGV-KLJ3adiDj  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   
...                                ...                   ...   
zburt5                             NaN                   NaN   
zebras                             NaN                   NaN   
zippy                              NaN                   NaN   
zitro                              NaN                   NaN   
zxcsdfd                            NaN                   NaN   

id                AV1Ys0kTvKc47QAVgx1C  AV1h6Gu0glJLPUi8IjA_  ...  \
reviews_username                                              ...   
1234                               NaN                   NaN  ...   
123charlie                         NaN                   NaN  ...   
37f5p                              NaN                   NaN  ...   
4cloroxl                           NaN                   NaN  ...   
50cal                              NaN                   NaN  ...   
...                                ...                   ...  ...   
zburt5                             NaN                   NaN  ...   
zebras                             NaN         

In [103]:
common_user_based_matrix.shape

(1660, 127)

#### common_user_based_matrix.shape

In [91]:
# Convert the user_correlation matrix into dataframe.
user_correlation_df = pd.DataFrame(user_correlation)

In [92]:
user_correlation_df.head(5)

0      1      2      3      4      5      6      7      8      9      ...  \
0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0  ...   

   18202  18203  18204  18205  18206  18207  18208  18209  18210  18211  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 18212 columns]

In [93]:
df_subtracted.head(5)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            NaN                   NaN  ...   
01impala                           NaN                   NaN  ...   
02dakota                           NaN                   NaN  ...   
02deuce                            NaN                   NaN  ...   
06stidriver                        NaN                   NaN  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfrgjFLJeJML43BvCc  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
06stidriver                        NaN                   NaN   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN               

In [94]:
user_correlation_df['userId'] = df_subtracted.index
user_correlation_df.set_index('userId',inplace=True)

user_correlation_df.columns = df_subtracted.index.tolist()
user_correlation_df.head()

00sab00  01impala  02dakota  02deuce  06stidriver  08dallas  \
userId                                                                     
00sab00          1.0       0.0       0.0      0.0          0.0       0.0   
01impala         0.0       1.0       0.0      0.0          0.0       0.0   
02dakota         0.0       0.0       1.0      0.0          0.0       0.0   
02deuce          0.0       0.0       0.0      1.0          0.0       0.0   
06stidriver      0.0       0.0       0.0      0.0          1.0       0.0   

             09mommy11  1.11E+24  1085  10ten  ...  zowie  zozo0o  zpalma  \
userId                                         ...                          
00sab00            0.0       0.0   0.0    0.0  ...    0.0     0.0     0.0   
01impala           0.0       0.0   0.0    0.0  ...    0.0     0.0     0.0   
02dakota           0.0       0.0   0.0    0.0  ...    0.0     0.0     0.0   
02deuce            0.0       0.0   0.0    0.0  ...    0.0     0.0     0.0   
06stidriver        0.0       0.0   0.0    0.0  ...    0.0     0.0     0.0   

             zsazsa  zt313  zuttle  zwithanx  zxcsdfd  zyiah4  zzz1127  
userId                                                                  
00sab00         0.0    0.0     0.0       0.0      0.0     0.0      0.0  
01impala        0.0    0.0     0.0       0.0      0.0     0.0      0.0  
02dakota        0.0    0.0     0.0       0.0      0.0     0.0      0.0  
02deuce         0.0    0.0     0.0       0.0      0.0     0.0      0.0  
06stidriver     0.0    0.0     0.0       0.0      0.0     0.0      0.0  

[5 rows x 18212 columns]

In [95]:
user_correlation_df.shape

(18212, 18212)

In [96]:
common.head(1)

id  reviews_rating reviews_username
21122  AVpfm8yiLJeJML43AYyu               1             jjjj

In [97]:
list_name = common.reviews_username.tolist()

user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]

In [98]:
user_correlation_df_1.shape

(1660, 18212)

In [99]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]

In [100]:
user_correlation_df_3 = user_correlation_df_2.T

In [101]:
user_correlation_df_3.shape

(1660, 1660)

In [102]:
user_correlation_df_3.head()

1234  123charlie  37f5p  4cloroxl  50cal  7.87E+11  aac06002  \
userId                                                                     
1234         1.0         0.0    0.0       0.0    0.0       0.0       0.0   
123charlie   0.0         1.0    0.0       0.0    0.0       0.0       0.0   
37f5p        0.0         0.0    1.0       0.0    0.0       0.0       0.0   
4cloroxl     0.0         0.0    0.0       1.0    0.0       0.0       0.0   
50cal        0.0         0.0    0.0       0.0    1.0       0.0       0.0   

            abbey  abbi  abby  ...  yesseniaw22  yeya  ygtz  yummy  zapman  \
userId                         ...                                           
1234          0.0   0.0   0.0  ...          0.0   0.0   0.0    0.0     0.0   
123charlie    0.0   0.0   0.0  ...          0.0   0.0   0.0    0.0     0.0   
37f5p         0.0   0.0   0.0  ...          0.0   0.0   0.0    0.0     0.0   
4cloroxl      0.0   0.0   0.0  ...          0.0   0.0   0.0    0.0     0.0   
50cal         0.0   0.0   0.0  ...          0.0   0.0   0.0    0.0     0.0   

            zburt5  zebras  zippy  zitro  zxcsdfd  
userId                                             
1234           0.0     0.0    0.0    0.0      0.0  
123charlie     0.0     0.0    0.0    0.0      0.0  
37f5p          0.0     0.0    0.0    0.0      0.0  
4cloroxl       0.0     0.0    0.0    0.0      0.0  
50cal          0.0     0.0    0.0    0.0      0.0  

[5 rows x 1660 columns]

In [104]:
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[0.28867513, 0.        , 0.        , ..., 2.5423759 , 1.44337567,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [105]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

In [106]:
dummy_test = pd.pivot_table(common, values='reviews_rating', index='reviews_username',
                                          columns='id', aggfunc='mean', fill_value=0)

In [107]:
dummy_test.shape

(1660, 127)

In [108]:
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)

In [156]:
common_user_predicted_ratings.head(5)

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
1234                               0.0                   0.0   
123charlie                         0.0                   0.0   
37f5p                              0.0                   0.0   
4cloroxl                           0.0                   0.0   
50cal                              0.0                   0.0   

id                AV1YlENIglJLPUi8IHsX  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
1234                               0.0                   0.0   
123charlie                         0.0                   0.0   
37f5p                              0.0                   0.0   
4cloroxl                           0.0                   0.0   
50cal                              0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  \
reviews_username                                               
1234                               0.0                   0.0   
123charlie                         0.0                   0.0   
37f5p                              0.0                   0.0   
4cloroxl                           0.0                   0.0   
50cal                              0.0                   0.0   

id                AV1YneDPglJLPUi8IJyQ  AV1YqAaMGV-KLJ3adiDj  \
reviews_username                                               
1234                               0.0                   0.0   
123charlie                         0.0                   0.0   
37f5p                              0.0                   0.0   
4cloroxl                           0.0                   0.0   
50cal                              0.0                   0.0   

id                AV1Ys0kTvKc47QAVgx1C  AV1h6Gu0glJLPUi8IjA_  ...  \
reviews_username                                              ...   
1234                               0.0                   0.0  ...   
123charlie                         0.0                   0.0  ...   
37f5p                              0.0                   0.0  ...   
4cloroxl                           0.0                   0.0  ...   
50cal                              0.0                   0.0  ...   

id                AVpfoSS51cnluZ0-oVH9  AVpfov9TLJeJML43A7B0  \
reviews_username                                               
1234                               0.0                   0.0   
123charlie                         0.0                   0.0   
37f5p                              0.0                   0.0   
4cloroxl                           0.0                   0.0   
50cal                              0.0                   0.0   

id                AVpfpM2yilAPnD_xfmDG  AVpfr5cb1cnluZ0-pZFp  \
reviews_username                                               
1234                               0.0                   0.0   
123charlie                         0.0                   0.0   
37f5p                              0.0                   0.0   
4cloroxl                           0.0                   0.0   
50cal                              0.0                   0.0   

id                AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
reviews_username                                               
1234                               0.0                   0.0   
123charlie                         0.0                   0.0   
37f5p                              0.0                   0.0   
4cloroxl                           0.0                   0.0   
50cal                              0.0                   0.0   

id                AVpfs0tUilAPnD_xgqN2  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
1234                               0.0                   0.0   
123charlie                         0.0                   0.0   
37f5p                              0.0                   0.0   
4cloroxl                           0.0               

Calculating the RMSE for only the pdts rated by user. For RMSE, normalising the rating to (1,5) range.

In [186]:
X  = common_user_predicted_ratings.copy() 
X = X.applymap(lambda x: np.NaN if x<=0 else x)

In [193]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(1, 5))

y = (scaler.fit_transform(X.T)).T
#y = scaler.fit_transform(X)

print(y)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [194]:
cdd= pd.DataFrame(y, index= X.index, columns= X.columns)

In [195]:
cdd.shape

(1660, 127)

In [196]:
common_user_based_matrix.head()

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   

id                AV1YlENIglJLPUi8IHsX  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   

id                AV1YneDPglJLPUi8IJyQ  AV1YqAaMGV-KLJ3adiDj  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   

id                AV1Ys0kTvKc47QAVgx1C  AV1h6Gu0glJLPUi8IjA_  ...  \
reviews_username                                              ...   
1234                               NaN                   NaN  ...   
123charlie                         NaN                   NaN  ...   
37f5p                              NaN                   NaN  ...   
4cloroxl                           NaN                   NaN  ...   
50cal                              NaN                   NaN  ...   

id                AVpfoSS51cnluZ0-oVH9  AVpfov9TLJeJML43A7B0  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   

id                AVpfpM2yilAPnD_xfmDG  AVpfr5cb1cnluZ0-pZFp  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   

id                AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN                   NaN   
50cal                              NaN                   NaN   

id                AVpfs0tUilAPnD_xgqN2  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
1234                               NaN                   NaN   
123charlie                         NaN                   NaN   
37f5p                              NaN                   NaN   
4cloroxl                           NaN               

In [197]:
# Finding total non-NaN value
total_non_nan = (~cdd.isnull()).sum().sum()
total_non_nan

1917

In [198]:
rmse = ((((common_user_based_matrix - cdd)**2).sum().sum())/total_non_nan)**0.5
print(rmse)

3.36287181717584


## Using Item similarity

# Item Based Similarity

Taking the transpose of the rating matrix to normalize the rating around the mean for different pdt ID. In the user based similarity, we had taken mean for each user instead of each pdt. 

In [199]:
df_pivot = pd.pivot_table(train, values='reviews_rating', index='id',
                                          columns='reviews_username', aggfunc='mean')

In [200]:
df_pivot.head()

reviews_username      00sab00  01impala  02dakota  02deuce  06stidriver  \
id                                                                        
AV13O1A8GV-KLJ3akUyj      NaN       NaN       NaN      NaN          NaN   
AV14LG0R-jtxr-f38QfS      NaN       NaN       NaN      NaN          NaN   
AV16khLE-jtxr-f38VFn      NaN       NaN       NaN      NaN          NaN   
AV1YGDqsGV-KLJ3adc-O      NaN       NaN       NaN      NaN          NaN   
AV1YIch7GV-KLJ3addeG      NaN       NaN       NaN      NaN          NaN   

reviews_username      08dallas  09mommy11  1.11E+24  1085  10ten  ...  zowie  \
id                                                                ...          
AV13O1A8GV-KLJ3akUyj       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV14LG0R-jtxr-f38QfS       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV16khLE-jtxr-f38VFn       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV1YGDqsGV-KLJ3adc-O       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV1YIch7GV-KLJ3addeG       NaN        NaN       NaN   NaN    NaN  ...    NaN   

reviews_username      zozo0o  zpalma  zsazsa  zt313  zuttle  zwithanx  \
id                                                                      
AV13O1A8GV-KLJ3akUyj     NaN     NaN     NaN    NaN     NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN     NaN     NaN    NaN     NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN     NaN     NaN    NaN     NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN     NaN     NaN    NaN     NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN     NaN     NaN    NaN     NaN       NaN   

reviews_username      zxcsdfd  zyiah4  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj      NaN     NaN      NaN  
AV14LG0R-jtxr-f38QfS      NaN     NaN      NaN  
AV16khLE-jtxr-f38VFn      NaN     NaN      NaN  
AV1YGDqsGV-KLJ3adc-O      NaN     NaN      NaN  
AV1YIch7GV-KLJ3addeG      NaN     NaN      NaN  

[5 rows x 18212 columns]

Normalising the pdt rating for each pdt for using the Adujsted Cosine

In [202]:
mean = np.nanmean(df_pivot, axis=1)
mean.shape

(255,)

In [203]:
df_subtracted= df_pivot.sub(mean, axis=0)

In [204]:
df_subtracted.head()

reviews_username      00sab00  01impala  02dakota  02deuce  06stidriver  \
id                                                                        
AV13O1A8GV-KLJ3akUyj      NaN       NaN       NaN      NaN          NaN   
AV14LG0R-jtxr-f38QfS      NaN       NaN       NaN      NaN          NaN   
AV16khLE-jtxr-f38VFn      NaN       NaN       NaN      NaN          NaN   
AV1YGDqsGV-KLJ3adc-O      NaN       NaN       NaN      NaN          NaN   
AV1YIch7GV-KLJ3addeG      NaN       NaN       NaN      NaN          NaN   

reviews_username      08dallas  09mommy11  1.11E+24  1085  10ten  ...  zowie  \
id                                                                ...          
AV13O1A8GV-KLJ3akUyj       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV14LG0R-jtxr-f38QfS       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV16khLE-jtxr-f38VFn       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV1YGDqsGV-KLJ3adc-O       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV1YIch7GV-KLJ3addeG       NaN        NaN       NaN   NaN    NaN  ...    NaN   

reviews_username      zozo0o  zpalma  zsazsa  zt313  zuttle  zwithanx  \
id                                                                      
AV13O1A8GV-KLJ3akUyj     NaN     NaN     NaN    NaN     NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN     NaN     NaN    NaN     NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN     NaN     NaN    NaN     NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN     NaN     NaN    NaN     NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN     NaN     NaN    NaN     NaN       NaN   

reviews_username      zxcsdfd  zyiah4  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj      NaN     NaN      NaN  
AV14LG0R-jtxr-f38QfS      NaN     NaN      NaN  
AV16khLE-jtxr-f38VFn      NaN     NaN      NaN  
AV1YGDqsGV-KLJ3adc-O      NaN     NaN      NaN  
AV1YIch7GV-KLJ3addeG      NaN     NaN      NaN  

[5 rows x 18212 columns]

Finding the cosine similarity using pairwise distances approach

In [208]:
from sklearn.metrics.pairwise import pairwise_distances

In [209]:
df_subtracted_array= df_subtracted.fillna(0).values

In [1]:
#help(pairwise_distances)

In [210]:
# Creating the User Similarity Matrix using pairwise_distance function.
item_correlation = 1 - pairwise_distances(df_subtracted_array, metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [237]:
item_correlation.shape

(255, 255)

In [244]:
#np.sum(item_correlation, axis=0)

In [215]:
df_pivot.head()

reviews_username      00sab00  01impala  02dakota  02deuce  06stidriver  \
id                                                                        
AV13O1A8GV-KLJ3akUyj      NaN       NaN       NaN      NaN          NaN   
AV14LG0R-jtxr-f38QfS      NaN       NaN       NaN      NaN          NaN   
AV16khLE-jtxr-f38VFn      NaN       NaN       NaN      NaN          NaN   
AV1YGDqsGV-KLJ3adc-O      NaN       NaN       NaN      NaN          NaN   
AV1YIch7GV-KLJ3addeG      NaN       NaN       NaN      NaN          NaN   

reviews_username      08dallas  09mommy11  1.11E+24  1085  10ten  ...  zowie  \
id                                                                ...          
AV13O1A8GV-KLJ3akUyj       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV14LG0R-jtxr-f38QfS       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV16khLE-jtxr-f38VFn       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV1YGDqsGV-KLJ3adc-O       NaN        NaN       NaN   NaN    NaN  ...    NaN   
AV1YIch7GV-KLJ3addeG       NaN        NaN       NaN   NaN    NaN  ...    NaN   

reviews_username      zozo0o  zpalma  zsazsa  zt313  zuttle  zwithanx  \
id                                                                      
AV13O1A8GV-KLJ3akUyj     NaN     NaN     NaN    NaN     NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN     NaN     NaN    NaN     NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN     NaN     NaN    NaN     NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN     NaN     NaN    NaN     NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN     NaN     NaN    NaN     NaN       NaN   

reviews_username      zxcsdfd  zyiah4  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj      NaN     NaN      NaN  
AV14LG0R-jtxr-f38QfS      NaN     NaN      NaN  
AV16khLE-jtxr-f38VFn      NaN     NaN      NaN  
AV1YGDqsGV-KLJ3adc-O      NaN     NaN      NaN  
AV1YIch7GV-KLJ3addeG      NaN     NaN      NaN  

[5 rows x 18212 columns]

Filtering the correlation only for which the value is greater than 0. (Positively correlated)

In [213]:
item_correlation[item_correlation<0]=0
item_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# Prediction - Item Item

In [216]:
item_predicted_ratings = np.dot(item_correlation, df_pivot.fillna(0))
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.01254045, 0.02090075, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.00600224, 0.00108461, 0.00180769, ..., 0.        , 0.        ,
        0.        ],
       [0.06201728, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00644332, 0.00644332,
        0.00515466]])

In [217]:
item_predicted_ratings.shape

(255, 18212)

In [218]:
dummy_train.shape

(18212, 255)

### Filtering the rating only for the pdts not rated by the user for recommendation

In [219]:
item_final_rating = np.multiply(dummy_train, item_predicted_ratings.T)
item_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
06stidriver                        0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                       0.000000              0.000000   
01impala                      0.012540              0.000000   
02dakota                      0.020901              0.000000   
02deuce                       0.016721              0.000000   
06stidriver                   0.000000              0.000454   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
06stidriver                        0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            0.0              0.000000   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0.000000   
06stidriver                        0.0              0.001731   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                       0.000000              0.000000  ...   
01impala                      0.000000              0.004564  ...   
02dakota                      0.000000              0.007607  ...   
02deuce                       0.000000              0.006085  ...   
06stidriver                   0.001915              0.000000  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
00sab00                       0.011345              0.001677   
01impala                      0.000000              0.000000   
02dakota                      0.000000              0.000000   
02deuce                       0.000000              0.000000   
06stidriver                   0.000000              0.000000   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
00sab00                            0.0              0.010336   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0.000000   
06stidriver                        0.0              0.003187   

id                AVpfrgjFLJeJML43BvCc  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
06stidriver                        0.0                   0.0   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                       0.033075              0.006002   
01impala                      0.000000              0.001085   
02dakota                      0.000000              0.001808   
02deuce                       0.000000              0

### Finding the top 5 recommendation for the *user*



In [221]:
# Take the user ID as input
user_input = input("Enter your user name")
print(user_input)

Enter your user name01impala
01impala


In [222]:
# Recommending the Top 5 products to the user.
d = item_final_rating.loc[user_input].sort_values(ascending=False)[0:5]
d

id
AVpe8q4T1cnluZ0-afct    0.051668
AVpe_5U_ilAPnD_xSrxG    0.035524
AVpe41TqilAPnD_xQH3d    0.027347
AV1ZSp2uglJLPUi8IQFy    0.025119
AVpfOmKwLJeJML435GM7    0.021629
Name: 01impala, dtype: float64

# Evaluation - Item Item

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the pdts already rated by the user insead of predicting it for the pdts not rated by the user. 

In [228]:
test.shape

(8982, 3)

In [229]:
test.columns

Index(['id', 'reviews_rating', 'reviews_username'], dtype='object')

In [230]:
common =  test[test.id.isin(train.id)]
common.shape

(8964, 3)

In [231]:
common.head(4)

id  reviews_rating reviews_username
21337  AVpfm8yiLJeJML43AYyu               1           curlyd
14441  AVpf3VOfilAPnD_xjpun               5             prip
21122  AVpfm8yiLJeJML43AYyu               1             jjjj
25359  AVpfPaoqLJeJML435Xk9               5  internetfreak69

In [232]:
common_item_based_matrix = pd.pivot_table(common, values='reviews_rating', index='id',
                                          columns='reviews_username', aggfunc='mean')

In [233]:
common_item_based_matrix.shape

(203, 8348)

In [234]:
item_correlation_df = pd.DataFrame(item_correlation)

In [236]:
item_correlation_df.head(2)

0    1    2    3    4    5    6    7    8    9    ...  245  246  247  248  \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   249  250  251  252  253  254  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  

[2 rows x 255 columns]

In [245]:
item_correlation_df['id'] = df_subtracted.index
item_correlation_df.set_index('id',inplace=True)
item_correlation_df.head()

0    1    2    3    4    5    6    7    8    9    ...  \
id                                                                      ...   
AV13O1A8GV-KLJ3akUyj  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
AV14LG0R-jtxr-f38QfS  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
AV16khLE-jtxr-f38VFn  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
AV1YGDqsGV-KLJ3adc-O  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
AV1YIch7GV-KLJ3addeG  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   

                           245  246  247  248  249  250  251       252  253  \
id                                                                            
AV13O1A8GV-KLJ3akUyj  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
AV14LG0R-jtxr-f38QfS  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
AV16khLE-jtxr-f38VFn  0.013954  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
AV1YGDqsGV-KLJ3adc-O  0.078102  0.0  0.0  0.0  0.0  0.0  0.0  0.001989  0.0   
AV1YIch7GV-KLJ3addeG  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   

                      254  
id                         
AV13O1A8GV-KLJ3akUyj  0.0  
AV14LG0R-jtxr-f38QfS  0.0  
AV16khLE-jtxr-f38VFn  0.0  
AV1YGDqsGV-KLJ3adc-O  0.0  
AV1YIch7GV-KLJ3addeG  0.0  

[5 rows x 255 columns]

In [247]:
list_name = common.id.tolist()

In [248]:
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]

In [249]:
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T

In [250]:
item_correlation_df_3.head()

AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
id                                                                 
AV16khLE-jtxr-f38VFn                   1.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   1.0   
AV1YlENIglJLPUi8IHsX                   0.0                   0.0   
AV1YmBrdGV-KLJ3adewb                   0.0                   0.0   
AV1YmDL9vKc47QAVgr7_                   0.0                   0.0   

                      AV1YlENIglJLPUi8IHsX  AV1YmBrdGV-KLJ3adewb  \
id                                                                 
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   
AV1YlENIglJLPUi8IHsX                   1.0                   0.0   
AV1YmBrdGV-KLJ3adewb                   0.0                   1.0   
AV1YmDL9vKc47QAVgr7_                   0.0                   0.0   

                      AV1YmDL9vKc47QAVgr7_  AV1Ymf_rglJLPUi8II2v  \
id                                                                 
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   
AV1YlENIglJLPUi8IHsX                   0.0                   0.0   
AV1YmBrdGV-KLJ3adewb                   0.0                   0.0   
AV1YmDL9vKc47QAVgr7_                   1.0                   0.0   

                      AV1Yn94nvKc47QAVgtst  AV1Ynb3bglJLPUi8IJxJ  \
id                                                                 
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   
AV1YlENIglJLPUi8IHsX                   0.0                   0.0   
AV1YmBrdGV-KLJ3adewb                   0.0                   0.0   
AV1YmDL9vKc47QAVgr7_                   0.0                   0.0   

                      AV1YneDPglJLPUi8IJyQ  AV1YqAaMGV-KLJ3adiDj  ...  \
id                                                                ...   
AV16khLE-jtxr-f38VFn              0.000000                   0.0  ...   
AV1YGDqsGV-KLJ3adc-O              0.003657                   0.0  ...   
AV1YlENIglJLPUi8IHsX              0.000000                   0.0  ...   
AV1YmBrdGV-KLJ3adewb              0.000000                   0.0  ...   
AV1YmDL9vKc47QAVgr7_              0.000000                   0.0  ...   

                      AVpfqW4WilAPnD_xf7a_  AVpfr5cb1cnluZ0-pZFp  \
id                                                                 
AV16khLE-jtxr-f38VFn                   0.0              0.013954   
AV1YGDqsGV-KLJ3adc-O                   0.0              0.078102   
AV1YlENIglJLPUi8IHsX                   0.0              0.000000   
AV1YmBrdGV-KLJ3adewb                   0.0              0.000000   
AV1YmDL9vKc47QAVgr7_                   0.0              0.000000   

                      AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
id                                                                 
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   
AV1YlENIglJLPUi8IHsX                   0.0                   0.0   
AV1YmBrdGV-KLJ3adewb                   0.0                   0.0   
AV1YmDL9vKc47QAVgr7_                   0.0                   0.0   

                      AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
id                                                                 
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   
AV1YlENIglJLPUi8IHsX                   0.0                   0.0   
AV1YmBrdGV-KLJ3adewb                   0.0                   0.0   
AV1YmDL9vKc47QAVgr7_                   0.0                   0.0   

                      AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
id                                                                 
AV16khLE-jtxr-f38VFn               

In [251]:
item_correlation_df_3.shape

(203, 203)

In [252]:
common_item_based_matrix.shape

(203, 8348)

In [253]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.02105944, 0.00045358, 0.00036287, ..., 0.00045358, 0.00018143,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00733409],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.10336214],
       [0.        , 0.00644332, 0.00515466, ..., 0.00644332, 0.00257733,
        0.        ]])

In [254]:
common_item_predicted_ratings.shape

(203, 8348)

Dummy test will be used for evaluation. To evaluate, we will only make prediction on the pdts rated by the user. So, this is marked as 1. This is just opposite of dummy_train



In [255]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

In [256]:
dummy_test = pd.pivot_table(common, values='reviews_rating', index='id',
                            columns='reviews_username', aggfunc='mean', fill_value=0)

In [257]:
dummy_test.shape

(203, 8348)

In [261]:
common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

In [262]:
common_item_predicted_ratings.head(5)

reviews_username      00dog3  0325home  1234  1234561  123cat123  123charlie  \
id                                                                             
AV16khLE-jtxr-f38VFn     0.0       0.0   0.0      0.0        0.0         0.0   
AV1YGDqsGV-KLJ3adc-O     0.0       0.0   0.0      0.0        0.0         0.0   
AV1YlENIglJLPUi8IHsX     0.0       0.0   0.0      0.0        0.0         0.0   
AV1YmBrdGV-KLJ3adewb     0.0       0.0   0.0      0.0        0.0         0.0   
AV1YmDL9vKc47QAVgr7_     0.0       0.0   0.0      0.0        0.0         0.0   

reviews_username      123numbers  127726  12cass12  1753  ...  zombie  \
id                                                        ...           
AV16khLE-jtxr-f38VFn         0.0     0.0       0.0   0.0  ...     0.0   
AV1YGDqsGV-KLJ3adc-O         0.0     0.0       0.0   0.0  ...     0.0   
AV1YlENIglJLPUi8IHsX         0.0     0.0       0.0   0.0  ...     0.0   
AV1YmBrdGV-KLJ3adewb         0.0     0.0       0.0   0.0  ...     0.0   
AV1YmDL9vKc47QAVgr7_         0.0     0.0       0.0   0.0  ...     0.0   

reviews_username      zombiedad80  zombiegirl22  zotox  zsarah  zubb  \
id                                                                     
AV16khLE-jtxr-f38VFn          0.0           0.0    0.0     0.0   0.0   
AV1YGDqsGV-KLJ3adc-O          0.0           0.0    0.0     0.0   0.0   
AV1YlENIglJLPUi8IHsX          0.0           0.0    0.0     0.0   0.0   
AV1YmBrdGV-KLJ3adewb          0.0           0.0    0.0     0.0   0.0   
AV1YmDL9vKc47QAVgr7_          0.0           0.0    0.0     0.0   0.0   

reviews_username      zulaa118  zxcsdfd  zxjki  zzdiane  
id                                                       
AV16khLE-jtxr-f38VFn       0.0      0.0    0.0      0.0  
AV1YGDqsGV-KLJ3adc-O       0.0      0.0    0.0      0.0  
AV1YlENIglJLPUi8IHsX       0.0      0.0    0.0      0.0  
AV1YmBrdGV-KLJ3adewb       0.0      0.0    0.0      0.0  
AV1YmDL9vKc47QAVgr7_       0.0      0.0    0.0      0.0  

[5 rows x 8348 columns]

Calculating the RMSE for only the pdts rated by user. For RMSE, normalising the rating to (1,5) range.

In [263]:
X  = common_item_predicted_ratings.copy() 
X = X.applymap(lambda x: np.NaN if x<=0 else x)

In [264]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(1, 5))

y = (scaler.fit_transform(X.T)).T
#y = scaler.fit_transform(X)

print(y)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [265]:
cdd= pd.DataFrame(y, index= X.index, columns= X.columns)

In [266]:
cdd.shape

(203, 8348)

In [268]:
common_item_based_matrix.head()

reviews_username      00dog3  0325home  1234  1234561  123cat123  123charlie  \
id                                                                             
AV16khLE-jtxr-f38VFn     NaN       NaN   NaN      NaN        NaN         NaN   
AV1YGDqsGV-KLJ3adc-O     NaN       NaN   NaN      NaN        NaN         NaN   
AV1YlENIglJLPUi8IHsX     NaN       NaN   NaN      NaN        NaN         NaN   
AV1YmBrdGV-KLJ3adewb     NaN       NaN   NaN      NaN        NaN         NaN   
AV1YmDL9vKc47QAVgr7_     NaN       NaN   NaN      NaN        NaN         NaN   

reviews_username      123numbers  127726  12cass12  1753  ...  zombie  \
id                                                        ...           
AV16khLE-jtxr-f38VFn         NaN     NaN       NaN   NaN  ...     NaN   
AV1YGDqsGV-KLJ3adc-O         NaN     NaN       NaN   NaN  ...     NaN   
AV1YlENIglJLPUi8IHsX         NaN     NaN       NaN   NaN  ...     NaN   
AV1YmBrdGV-KLJ3adewb         NaN     NaN       NaN   NaN  ...     NaN   
AV1YmDL9vKc47QAVgr7_         NaN     NaN       NaN   NaN  ...     NaN   

reviews_username      zombiedad80  zombiegirl22  zotox  zsarah  zubb  \
id                                                                     
AV16khLE-jtxr-f38VFn          NaN           NaN    NaN     NaN   NaN   
AV1YGDqsGV-KLJ3adc-O          NaN           NaN    NaN     NaN   NaN   
AV1YlENIglJLPUi8IHsX          NaN           NaN    NaN     NaN   NaN   
AV1YmBrdGV-KLJ3adewb          NaN           NaN    NaN     NaN   NaN   
AV1YmDL9vKc47QAVgr7_          NaN           NaN    NaN     NaN   NaN   

reviews_username      zulaa118  zxcsdfd  zxjki  zzdiane  
id                                                       
AV16khLE-jtxr-f38VFn       NaN      NaN    NaN      NaN  
AV1YGDqsGV-KLJ3adc-O       NaN      NaN    NaN      NaN  
AV1YlENIglJLPUi8IHsX       NaN      NaN    NaN      NaN  
AV1YmBrdGV-KLJ3adewb       NaN      NaN    NaN      NaN  
AV1YmDL9vKc47QAVgr7_       NaN      NaN    NaN      NaN  

[5 rows x 8348 columns]

In [269]:
# Finding total non-NaN value
total_non_nan = (~cdd.isnull()).sum().sum()
total_non_nan

8738

In [270]:
rmse = ((((common_item_based_matrix - cdd)**2).sum().sum())/total_non_nan)**0.5
print(rmse)

0.7254748734687848


### Clearly we can see that item based collaborative engines work better than user based as the rmse is less.

### So finally we will take the whole dataset and build a reco engine which will be used for our model.

In [272]:
ratings.head()

id  reviews_rating reviews_username
0  AV13O1A8GV-KLJ3akUyj               5           joshua
1  AV14LG0R-jtxr-f38QfS               5        dorothy w
2  AV14LG0R-jtxr-f38QfS               5        dorothy w
3  AV16khLE-jtxr-f38VFn               1          rebecca
4  AV16khLE-jtxr-f38VFn               1        walker557

In [273]:
ratings.shape

(29937, 3)

In [274]:
ratings['id'].nunique()

271

In [275]:
ratings['reviews_username'].nunique()

24914

In [276]:
df_pivot = pd.pivot_table(ratings, values='reviews_rating', index='id',
                          columns='reviews_username', aggfunc='mean')

In [277]:
df_pivot.head()

reviews_username      00dog3  00sab00  01impala  02dakota  02deuce  0325home  \
id                                                                             
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN       NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN       NaN      NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN      NaN       NaN       NaN      NaN       NaN   

reviews_username      06stidriver  08dallas  09mommy11  1.11E+24  ...  zt313  \
id                                                                ...          
AV13O1A8GV-KLJ3akUyj          NaN       NaN        NaN       NaN  ...    NaN   
AV14LG0R-jtxr-f38QfS          NaN       NaN        NaN       NaN  ...    NaN   
AV16khLE-jtxr-f38VFn          NaN       NaN        NaN       NaN  ...    NaN   
AV1YGDqsGV-KLJ3adc-O          NaN       NaN        NaN       NaN  ...    NaN   
AV1YIch7GV-KLJ3addeG          NaN       NaN        NaN       NaN  ...    NaN   

reviews_username      zubb  zulaa118  zuttle  zwithanx  zxcsdfd  zxjki  \
id                                                                       
AV13O1A8GV-KLJ3akUyj   NaN       NaN     NaN       NaN      NaN    NaN   
AV14LG0R-jtxr-f38QfS   NaN       NaN     NaN       NaN      NaN    NaN   
AV16khLE-jtxr-f38VFn   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YGDqsGV-KLJ3adc-O   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YIch7GV-KLJ3addeG   NaN       NaN     NaN       NaN      NaN    NaN   

reviews_username      zyiah4  zzdiane  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj     NaN      NaN      NaN  
AV14LG0R-jtxr-f38QfS     NaN      NaN      NaN  
AV16khLE-jtxr-f38VFn     NaN      NaN      NaN  
AV1YGDqsGV-KLJ3adc-O     NaN      NaN      NaN  
AV1YIch7GV-KLJ3addeG     NaN      NaN      NaN  

[5 rows x 24914 columns]

Normalising the pdt rating for each pdt for using the Adujsted Cosine

In [278]:
mean = np.nanmean(df_pivot, axis=1)
mean.shape

(271,)

In [279]:
df_subtracted= df_pivot.sub(mean, axis=0)

In [280]:
df_subtracted.head()

reviews_username      00dog3  00sab00  01impala  02dakota  02deuce  0325home  \
id                                                                             
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN       NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN       NaN      NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN      NaN       NaN       NaN      NaN       NaN   

reviews_username      06stidriver  08dallas  09mommy11  1.11E+24  ...  zt313  \
id                                                                ...          
AV13O1A8GV-KLJ3akUyj          NaN       NaN        NaN       NaN  ...    NaN   
AV14LG0R-jtxr-f38QfS          NaN       NaN        NaN       NaN  ...    NaN   
AV16khLE-jtxr-f38VFn          NaN       NaN        NaN       NaN  ...    NaN   
AV1YGDqsGV-KLJ3adc-O          NaN       NaN        NaN       NaN  ...    NaN   
AV1YIch7GV-KLJ3addeG          NaN       NaN        NaN       NaN  ...    NaN   

reviews_username      zubb  zulaa118  zuttle  zwithanx  zxcsdfd  zxjki  \
id                                                                       
AV13O1A8GV-KLJ3akUyj   NaN       NaN     NaN       NaN      NaN    NaN   
AV14LG0R-jtxr-f38QfS   NaN       NaN     NaN       NaN      NaN    NaN   
AV16khLE-jtxr-f38VFn   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YGDqsGV-KLJ3adc-O   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YIch7GV-KLJ3addeG   NaN       NaN     NaN       NaN      NaN    NaN   

reviews_username      zyiah4  zzdiane  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj     NaN      NaN      NaN  
AV14LG0R-jtxr-f38QfS     NaN      NaN      NaN  
AV16khLE-jtxr-f38VFn     NaN      NaN      NaN  
AV1YGDqsGV-KLJ3adc-O     NaN      NaN      NaN  
AV1YIch7GV-KLJ3addeG     NaN      NaN      NaN  

[5 rows x 24914 columns]

Finding the cosine similarity using pairwise distances approach

In [281]:
from sklearn.metrics.pairwise import pairwise_distances

In [282]:
df_subtracted_array= df_subtracted.fillna(0).values

In [283]:
#help(pairwise_distances)

In [284]:
# Creating the User Similarity Matrix using pairwise_distance function.
item_correlation = 1 - pairwise_distances(df_subtracted_array, metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [285]:
item_correlation.shape

(271, 271)

In [289]:
df_pivot.shape

(271, 24914)

In [287]:
df_pivot.head()

reviews_username      00dog3  00sab00  01impala  02dakota  02deuce  0325home  \
id                                                                             
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN       NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN       NaN      NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN       NaN      NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN      NaN       NaN       NaN      NaN       NaN   

reviews_username      06stidriver  08dallas  09mommy11  1.11E+24  ...  zt313  \
id                                                                ...          
AV13O1A8GV-KLJ3akUyj          NaN       NaN        NaN       NaN  ...    NaN   
AV14LG0R-jtxr-f38QfS          NaN       NaN        NaN       NaN  ...    NaN   
AV16khLE-jtxr-f38VFn          NaN       NaN        NaN       NaN  ...    NaN   
AV1YGDqsGV-KLJ3adc-O          NaN       NaN        NaN       NaN  ...    NaN   
AV1YIch7GV-KLJ3addeG          NaN       NaN        NaN       NaN  ...    NaN   

reviews_username      zubb  zulaa118  zuttle  zwithanx  zxcsdfd  zxjki  \
id                                                                       
AV13O1A8GV-KLJ3akUyj   NaN       NaN     NaN       NaN      NaN    NaN   
AV14LG0R-jtxr-f38QfS   NaN       NaN     NaN       NaN      NaN    NaN   
AV16khLE-jtxr-f38VFn   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YGDqsGV-KLJ3adc-O   NaN       NaN     NaN       NaN      NaN    NaN   
AV1YIch7GV-KLJ3addeG   NaN       NaN     NaN       NaN      NaN    NaN   

reviews_username      zyiah4  zzdiane  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj     NaN      NaN      NaN  
AV14LG0R-jtxr-f38QfS     NaN      NaN      NaN  
AV16khLE-jtxr-f38VFn     NaN      NaN      NaN  
AV1YGDqsGV-KLJ3adc-O     NaN      NaN      NaN  
AV1YIch7GV-KLJ3addeG     NaN      NaN      NaN  

[5 rows x 24914 columns]

Filtering the correlation only for which the value is greater than 0. (Positively correlated)

In [288]:
item_correlation[item_correlation<0]=0
item_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# Prediction - Item Item

In [290]:
item_predicted_ratings = np.dot(item_correlation, df_pivot.fillna(0))
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.00928264, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.0304546 , 0.        , ..., 0.        , 0.05075767,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00498975, 0.        ,
        0.0039918 ]])

In [291]:
item_predicted_ratings.shape

(271, 24914)

In [292]:
# Copy the whole dataset into dummy
dummy = ratings.copy()

In [293]:
# The pdt not rated by user is marked as 1 for prediction. 
dummy['reviews_rating'] = 0

In [294]:
# Pivot the train ratings' dataset into matrix format in which columns are ids and the rows are username.
dummy = pd.pivot_table(dummy, values='reviews_rating', index='id',
                          columns='reviews_username', aggfunc='mean', fill_value=1)

In [295]:
dummy.shape

(271, 24914)

### Filtering the rating only for the pdts not rated by the user for recommendation

In [311]:
item_final_rating = np.multiply(dummy, item_predicted_ratings).T
item_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00dog3                        0.000000              0.013962   
00sab00                       0.000000              0.000628   
01impala                      0.009283              0.000000   
02dakota                      0.015471              0.000000   
02deuce                       0.012377              0.000000   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00dog3                             0.0              0.000000  ...   
00sab00                            0.0              0.004400  ...   
01impala                           0.0              0.004272  ...   
02dakota                           0.0              0.007121  ...   
02deuce                            0.0              0.005696  ...   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
00dog3                        0.000000                   0.0   
00sab00                       0.008822                   0.0   
01impala                      0.000000                   0.0   
02dakota                      0.000000                   0.0   
02deuce                       0.000000                   0.0   

id                AVpfs0tUilAPnD_xgqN2  AVpfsQoeilAPnD_xgfx5  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   

id                AVpfshNsLJeJML43CB8q  AVpfthSailAPnD_xg3ON  \
reviews_username                                               
00dog3                             0.0              0.000000   
00sab00                            0.0              0.023173   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0.000000   

id                AVpftikC1cnluZ0-p31V  AVpftymALJeJML43CZ6y  \
reviews_username                                               
00dog3                        0.000000                   0.0   
00sab00                       0.004476                   0.0   
01impala                      0.000000                   0.0   
02dakota                      0.000000               

In [319]:
item_final_rating.head(10)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00dog3                        0.000000              0.013962   
00sab00                       0.000000              0.000628   
01impala                      0.009283              0.000000   
02dakota                      0.015471              0.000000   
02deuce                       0.012377              0.000000   
0325home                      0.000000              0.000000   
06stidriver                   0.000000              0.000000   
08dallas                      0.000000              0.000000   
09mommy11                     0.000000              0.058648   
1.11E+24                      0.000000              0.000000   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00dog3                             0.0               0.00000   
00sab00                            0.0               0.00000   
01impala                           0.0               0.00000   
02dakota                           0.0               0.00000   
02deuce                            0.0               0.00000   
0325home                           0.0               0.00121   
06stidriver                        0.0               0.00121   
08dallas                           0.0               0.00000   
09mommy11                          0.0               0.00267   
1.11E+24                           0.0               0.00121   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00dog3                        0.000000              0.000000  ...   
00sab00                       0.000000              0.004400  ...   
01impala                      0.000000              0.004272  ...   
02dakota                      0.000000              0.007121  ...   
02deuce                       0.000000              0.005696  ...   
0325home                      0.002909              0.002740  ...   
06stidriver                   0.002909              0.002740  ...   
08dallas                      0.000000              0.000000  ...   
09mommy11                     0.447822              0.000000  ...   
1.11E+24                      0.002909              0.002740  ...   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username               

In [312]:
item_final_rating.shape

(24914, 271)

Saving the final ratings in a csv file for future use.

In [316]:
item_final_rating.to_csv('Dataset/item_based_reco.csv', float_format="%.2f")

In [2]:
def get_20_pdt_id(username):
    enq= pd.read_csv('Dataset/item_based_reco.csv')
    enq.set_index('reviews_username', inplace=True)
    d= enq.loc[username].sort_values(ascending=False)[0:20]
    return list(d.index)

In [3]:
get_20_pdt_id('02deuce')

['AVpf5olc1cnluZ0-tPrO',
 'AVpfrTyiLJeJML43BrSI',
 'AVpf4WWN1cnluZ0-s7Wj',
 'AVpfBU2S1cnluZ0-cJsO',
 'AVpfRTh1ilAPnD_xYic2',
 'AVpe8q4T1cnluZ0-afct',
 'AVpf0pfrilAPnD_xi6s_',
 'AVpfR5m0LJeJML436K3W',
 'AVpfOmKwLJeJML435GM7',
 'AVpe41TqilAPnD_xQH3d',
 'AVpe_5U_ilAPnD_xSrxG',
 'AVpfbraG1cnluZ0-kqnn',
 'AVpe6PCDLJeJML43yFQH',
 'AVpfnRuSilAPnD_xfB8l',
 'AVpf7I3i1cnluZ0-tnL6',
 'AVpf7LysilAPnD_xkm9G',
 'AVpe8dHWLJeJML43y4uG',
 'AVpe5c23LJeJML43xybi',
 'AVpe5JOgilAPnD_xQPfE',
 'AVpfAkX91cnluZ0-b4d8']

## Deployment Code:

This below codes are used to generate the top 5 recommendations based on the username. We deliberatly put it into classes so that we can move it directly to model.py file. 

The process would be as follows the user gives the input. System will predict top 20 pdts based on item-item collaborative reco engine which is saved as a excel file. Out of this top 20, system will again go through one by one, fetch all the review text from the dataset and process it on the go with tf-idf and predict the sentiment using logistic regression model for each reviews, from which the overall sentiment can be calculated for any product. Likewise every top 20 product would have their overall sentiment, out of which only top 5 is taken and given as output.

The main issue with this is processing all the reviews and preicting the sentiment is time consuming because of which at the time of deployment, it is taking 2-3 mins to give the output.


In [1]:
import re # for regular expressions
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from spellchecker import SpellChecker
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import pickle

words_removed= ['collect', 'part', 'promote', 'review', 'really', 'product']

stemmer = PorterStemmer()

spell = SpellChecker()

with open('models/logreg_model.pkl', 'rb') as file:
    model = pickle.load(file)
    
with open('models/tf-idf.pkl', 'rb') as file:
    tf_idf = pickle.load(file)
    

class get_sentiment():
    
    def __init__(self):
        
        return None
    
    def clean_review(self, review_text):
        review_text = re.sub(r"http\S+", "", review_text)                         ## remove the urls
        review_text = re.sub("[^a-zA-Z]", " ", review_text)                       ## remove numbers and puncuation
        review_text = str(review_text).lower()                                    ## converting into lower case
        review_text = word_tokenize(review_text)                                  ## tokenization
        review_text = [i for i in review_text if len(i)>2]                        ## remove the words having length less than 2
        review_text = [i for i in review_text if i not in stopwords.words('english')]  ## remove stop words
        review_text = [i for i in review_text if i not in words_removed]
        review_text = [stemmer.stem(i) for i in review_text]                           ## stemming 
        review_text = [spell.correction(i) for i in review_text]                       ## spell correction
        review_text = ' '.join(review_text)
        
        return(review_text)
    
    def sentiment (self, review_text):
        
        review_text = self.clean_review(review_text)
        
        X = tf_idf.transform([review_text])
        
        y= model.predict(X)
        
        return(int(y))
        
        

In [2]:
#dataset = pd.read_csv('sample30.csv')
#dataset['id'].value_counts()[:20]

In [3]:
import pandas as pd
import numpy as np
import random

item_based_reco = pd.read_csv('Dataset/item_based_reco.csv')
item_based_reco.set_index('reviews_username', inplace=True)

dataset = pd.read_csv('Dataset/sample30.csv')

id_name= pd.read_csv('Dataset/id_name.csv')

class pdt_recommendation(get_sentiment):
    
    def __init__(self):
        
        #self.username= username
        return None
    
    
    def recom_using_item_based(self, username): ##takes username as input and returns 20 reco pdts
        
        d = item_based_reco.loc[username].sort_values(ascending=False)[0:20]
        top_20 = list(d.index)
        
        return top_20
    
    def pdt_overall_sentiment(self, pdt_id): ##takes a pdt id as input serach the reviews and give the sentiment_score
        
        filt_df= dataset.loc[dataset['id']== pdt_id, ['reviews_title', 'reviews_text']]
        filt_df['merge']= filt_df['reviews_title']+ str(' ')+ filt_df['reviews_text']
        all_reviews = list(filt_df['merge'])
        
        #if len(all_reviews)>300:
        #    all_reviews= random.sample(all_reviews, 300)
        
        #print(len(all_reviews))
        
        sentiment_score= sum([self.sentiment(str(review)) for review in all_reviews])
        
        return (round(sentiment_score/len(all_reviews),2))
    
    def predict(self, username):
        
        top_20_pdt_id= self.recom_using_item_based(username)
        top_20_pdt_sent={}
        for id in top_20_pdt_id:
            top_20_pdt_sent[id] = self.pdt_overall_sentiment(id)
            
        top_20_pdt_sent= dict(sorted(top_20_pdt_sent.items(), key= (lambda x: -x[1])))

        top_5_pdt_id= list(top_20_pdt_sent.keys())[0:5]
        
        
        top_5_pdt_name= [id_name.loc[id_name['id']==x , 'name_with_brand'].values[0] for x in top_5_pdt_id]
        
        
        return(top_5_pdt_name)
            
        

In [4]:
import timeit

start = timeit.default_timer()

aa= pdt_recommendation()
xd= aa.predict('09mommy11')
print(xd)

stop = timeit.default_timer()

["L'or233al Paris Elvive Extraordinary Clay Rebalancing Conditioner - 12.6 Fl Oz by L'oreal Paris", 'Boraam Sonoma Kitchen Cart With Wire Brush Gray - Maaya Home by Maaya Home', 'Yes To Carrots Nourishing Body Wash by Yes to Carrots', 'Stander Pt Bedcane - Bed Handle by Stander', 'Planes: Fire Rescue (2 Discs) (includes Digital Copy) (blu-Ray/dvd) by Disney']


In [5]:
print('Time: ', stop - start)

Time:  2579.0153229999996


The solution can be to predict the overall sentiment for every product earlier and save it in a csv file to fetch the results later. This can be done because here our product and review dataset is not changing.

In [7]:
#dataset.head()

In [8]:
aa= pdt_recommendation()

In [9]:
id_name.head()

id                                    name_with_brand
0  AV13O1A8GV-KLJ3akUyj  Pink Friday: Roman Reloaded Re-Up (w/dvd) by U...
1  AV14LG0R-jtxr-f38QfS  Lundberg Organic Cinnamon Toast Rice Cakes by ...
2  AV16khLE-jtxr-f38VFn            K-Y Love Sensuality Pleasure Gel by K-Y
3  AV1d76w7vKc47QAVhCqn  J.R. Watkins Hand Cream, Lemon Cream by J.R. W...
4  AV1h6gSl-jtxr-f31p40              Ambi Complexion Cleansing Bar by AMBI

In [7]:
id_name['overall_sentiment']= id_name['id'].apply(aa.pdt_overall_sentiment)

In [9]:
id_name.head()

id                                    name_with_brand  \
0  AV13O1A8GV-KLJ3akUyj  Pink Friday: Roman Reloaded Re-Up (w/dvd) by U...   
1  AV14LG0R-jtxr-f38QfS  Lundberg Organic Cinnamon Toast Rice Cakes by ...   
2  AV16khLE-jtxr-f38VFn            K-Y Love Sensuality Pleasure Gel by K-Y   
3  AV1d76w7vKc47QAVhCqn  J.R. Watkins Hand Cream, Lemon Cream by J.R. W...   
4  AV1h6gSl-jtxr-f31p40              Ambi Complexion Cleansing Bar by AMBI   

   overall_sentiment  
0               1.00  
1               1.00  
2               0.41  
3               0.83  
4               0.75

In [10]:
id_name.to_csv('Dataset/id_name_sentiment.csv', index=False)

In [11]:
id_name_sent= pd.read_csv('Dataset/id_name_sentiment.csv')
id_name_sent.head()

id                                    name_with_brand  \
0  AV13O1A8GV-KLJ3akUyj  Pink Friday: Roman Reloaded Re-Up (w/dvd) by U...   
1  AV14LG0R-jtxr-f38QfS  Lundberg Organic Cinnamon Toast Rice Cakes by ...   
2  AV16khLE-jtxr-f38VFn            K-Y Love Sensuality Pleasure Gel by K-Y   
3  AV1d76w7vKc47QAVhCqn  J.R. Watkins Hand Cream, Lemon Cream by J.R. W...   
4  AV1h6gSl-jtxr-f31p40              Ambi Complexion Cleansing Bar by AMBI   

   overall_sentiment  
0               1.00  
1               1.00  
2               0.41  
3               0.83  
4               0.75

In [15]:
id_name_sent.loc[id_name_sent['id']== 'AV1d76w7vKc47QAVhCqn', 'overall_sentiment'].values[0]

0.83

In [1]:
import pandas as pd
import numpy as np
import random

item_based_reco = pd.read_csv('Dataset/item_based_reco.csv')
item_based_reco.set_index('reviews_username', inplace=True)

id_name_sent= pd.read_csv('Dataset/id_name_sentiment.csv')

class pdt_recommendation():
    
    def __init__(self):
        
        #self.username= username
        return None
    
    
    def recom_using_item_based(self, username): ##takes username as input and returns 20 reco pdts
        
        d = item_based_reco.loc[username].sort_values(ascending=False)[0:20]
        top_20 = list(d.index)
        
        return top_20
    
    def pdt_overall_sentiment(self, pdt_id): ##takes a pdt id as input serach the reviews and give the sentiment_score
        
        sentiment_score= id_name_sent.loc[id_name_sent['id']== pdt_id, 'overall_sentiment'].values[0]
        
        return (sentiment_score)
    
    def predict(self, username):
        
        top_20_pdt_id= self.recom_using_item_based(username)
        top_20_pdt_sent={}
        for id in top_20_pdt_id:
            top_20_pdt_sent[id] = self.pdt_overall_sentiment(id)
            
        top_20_pdt_sent= dict(sorted(top_20_pdt_sent.items(), key= (lambda x: -x[1])))

        top_5_pdt_id= list(top_20_pdt_sent.keys())[0:5]
        
        
        top_5_pdt_name= [id_name_sent.loc[id_name_sent['id']== x , 'name_with_brand'].values[0] for x in top_5_pdt_id]
        
        
        return(top_5_pdt_name)
        

In [2]:
aa= pdt_recommendation()
aa.predict('09mommy11')

["L'or233al Paris Elvive Extraordinary Clay Rebalancing Conditioner - 12.6 Fl Oz by L'oreal Paris",
 'Boraam Sonoma Kitchen Cart With Wire Brush Gray - Maaya Home by Maaya Home',
 'Yes To Carrots Nourishing Body Wash by Yes to Carrots',
 'Stander Pt Bedcane - Bed Handle by Stander',
 'Planes: Fire Rescue (2 Discs) (includes Digital Copy) (blu-Ray/dvd) by Disney']